// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace NET6Demo.Model
{
    public partial class log
    {
        [Key]
        public int Id { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? log_datetime { get; set; }
        [StringLength(255)]
        public string? log_thread { get; set; }
        [StringLength(50)]
        public string? log_level { get; set; }
        [StringLength(255)]
        public string? log_logger { get; set; }
        [StringLength(10000)]
        public string? log_message { get; set; }
    }
}