// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace NET6Demo.Model
{
    [Index("StatusId", Name = "tb_info_power_ibfk_1")]
    public partial class tb_info_power
    {
        public tb_info_power()
        {
            tb_map_role_power = new HashSet<tb_map_role_power>();
            tb_map_user_power = new HashSet<tb_map_user_power>();
        }

        [Key]
        public int Id { get; set; }
        /// <summary>
        /// 权限名称
        /// </summary>
        [StringLength(255)]
        public string? PowerName { get; set; }
        /// <summary>
        /// 权限说明
        /// </summary>
        [StringLength(1000)]
        public string? Note { get; set; }
        /// <summary>
        /// 授权页面
        /// </summary>
        [StringLength(3000)]
        public string? Url { get; set; }
        /// <summary>
        /// 权限code
        /// </summary>
        [StringLength(100)]
        public string? PowerCode { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime CreateAt { get; set; }
        /// <summary>
        /// 权限模块
        /// </summary>
        [StringLength(255)]
        public string? PowerModule { get; set; }
        /// <summary>
        /// 状态Id
        /// </summary>
        public int? StatusId { get; set; }
        /// <summary>
        /// 权限方法
        /// </summary>
        [StringLength(255)]
        public string? FuncName { get; set; }
        public int? CreateUserId { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? ModifyAt { get; set; }
        public int? ModifyUserId { get; set; }

        [ForeignKey("StatusId")]
        [InverseProperty("tb_info_power")]
        public virtual tb_info_status? Status { get; set; }
        [InverseProperty("Power")]
        public virtual ICollection<tb_map_role_power> tb_map_role_power { get; set; }
        [InverseProperty("Power")]
        public virtual ICollection<tb_map_user_power> tb_map_user_power { get; set; }
    }
}