// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace NET6Demo.Model
{
    [Index("Status", Name = "tb_info_user_ibfk_1")]
    public partial class tb_info_user
    {
        public tb_info_user()
        {
            tb_map_user_org = new HashSet<tb_map_user_org>();
            tb_map_user_power = new HashSet<tb_map_user_power>();
            tb_map_user_roles = new HashSet<tb_map_user_roles>();
            tb_rec_authorize = new HashSet<tb_rec_authorize>();
        }

        [Key]
        public int Id { get; set; }
        /// <summary>
        /// 用户名称（昵称）
        /// </summary>
        [StringLength(255)]
        public string? UserName { get; set; }
        /// <summary>
        /// 密码（密文）
        /// </summary>
        [StringLength(50)]
        public string? password { get; set; }
        [StringLength(255)]
        public string? Email { get; set; }
        [StringLength(255)]
        public string? Phone { get; set; }
        /// <summary>
        /// 微信unionId
        /// </summary>
        [StringLength(255)]
        public string? WxUnionId { get; set; }
        /// <summary>
        /// 微信OpendId
        /// </summary>
        [StringLength(255)]
        public string? WxOpenId { get; set; }
        /// <summary>
        /// 微信nickname
        /// </summary>
        [StringLength(255)]
        public string? Nickname { get; set; }
        /// <summary>
        /// 微信头像headimgurl
        /// </summary>
        [StringLength(1000)]
        public string? headimgurl { get; set; }
        /// <summary>
        /// 身份证号
        /// </summary>
        [StringLength(100)]
        public string? IdNum { get; set; }
        /// <summary>
        /// 状态
        /// </summary>
        public int? Status { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime CreateAt { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? ModifyAt { get; set; }
        /// <summary>
        /// 用户代码
        /// </summary>
        [StringLength(100)]
        public string? UserCode { get; set; }

        [ForeignKey("Status")]
        [InverseProperty("tb_info_user")]
        public virtual tb_info_status? StatusNavigation { get; set; }
        [InverseProperty("User")]
        public virtual ICollection<tb_map_user_org> tb_map_user_org { get; set; }
        [InverseProperty("User")]
        public virtual ICollection<tb_map_user_power> tb_map_user_power { get; set; }
        [InverseProperty("User")]
        public virtual ICollection<tb_map_user_roles> tb_map_user_roles { get; set; }
        [InverseProperty("User")]
        public virtual ICollection<tb_rec_authorize> tb_rec_authorize { get; set; }
    }
}