// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace NET6Demo.Model
{
    [Index("CreateUserId", Name = "CreateUserId")]
    [Index("ModifyUserId", Name = "ModifyUserId")]
    [Index("StatusId", Name = "tb_info_org_ibfk_1")]
    [Index("OrgTypeId", Name = "tb_info_org_ibfk_2")]
    public partial class tb_info_org
    {
        public tb_info_org()
        {
            tb_map_user_org = new HashSet<tb_map_user_org>();
            tb_rec_license = new HashSet<tb_rec_license>();
        }

        [Key]
        public int Id { get; set; }
        /// <summary>
        /// 组织名称
        /// </summary>
        [StringLength(255)]
        public string? OrgName { get; set; }
        /// <summary>
        /// 组织编码
        /// </summary>
        [StringLength(100)]
        public string? OrgCode { get; set; }
        /// <summary>
        /// 状态ID
        /// </summary>
        public int? StatusId { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime CreateAt { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? ModifyAt { get; set; }
        /// <summary>
        /// 组织类型Id
        /// </summary>
        public int? OrgTypeId { get; set; }
        public int? CreateUserId { get; set; }
        public int? ModifyUserId { get; set; }

        [ForeignKey("OrgTypeId")]
        [InverseProperty("tb_info_org")]
        public virtual tb_info_orgtype? OrgType { get; set; }
        [ForeignKey("StatusId")]
        [InverseProperty("tb_info_org")]
        public virtual tb_info_status? Status { get; set; }
        [InverseProperty("Org")]
        public virtual ICollection<tb_map_user_org> tb_map_user_org { get; set; }
        [InverseProperty("Org")]
        public virtual ICollection<tb_rec_license> tb_rec_license { get; set; }
    }
}