// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace NET6Demo.Model
{
    [Index("CreateUserId", Name = "CreateUserId")]
    [Index("ModifyUserId", Name = "ModifyUserId")]
    [Index("StatusId", Name = "StatusId")]
    public partial class tb_info_licesen
    {
        public tb_info_licesen()
        {
            tb_rec_license = new HashSet<tb_rec_license>();
        }

        [Key]
        public int Id { get; set; }
        /// <summary>
        /// 授权类型名称
        /// </summary>
        [StringLength(255)]
        public string? Typename { get; set; }
        /// <summary>
        /// 授权类型说明
        /// </summary>
        [StringLength(1000)]
        public string? Note { get; set; }
        public int? StatusId { get; set; }
        /// <summary>
        /// 建立时间
        /// </summary>
        [Column(TypeName = "datetime")]
        public DateTime CreateAt { get; set; }
        /// <summary>
        /// 最后修改时间
        /// </summary>
        [Column(TypeName = "datetime")]
        public DateTime? ModifyAt { get; set; }
        /// <summary>
        /// 建立用户
        /// </summary>
        public int? CreateUserId { get; set; }
        /// <summary>
        /// 最后修改用户
        /// </summary>
        public int? ModifyUserId { get; set; }

        [ForeignKey("StatusId")]
        [InverseProperty("tb_info_licesen")]
        public virtual tb_info_status? Status { get; set; }
        [InverseProperty("licensetypeNavigation")]
        public virtual ICollection<tb_rec_license> tb_rec_license { get; set; }
    }
}