// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace NET6Demo.Model
{
    /// <summary>
    /// 用户权限是指用户的特殊权限，存在于用户角色之外的。如果在用户角色之内的，请通过角色获取，这里单指定特殊权限
    /// </summary>
    [Index("UserId", Name = "tb_map_user_power_ibfk_1")]
    [Index("PowerId", Name = "tb_map_user_power_ibfk_2")]
    [Index("StatusId", Name = "tb_map_user_power_ibfk_3")]
    public partial class tb_map_user_power
    {
        public tb_map_user_power()
        {
            tb_rec_authorize = new HashSet<tb_rec_authorize>();
        }

        [Key]
        public int Id { get; set; }
        /// <summary>
        /// 用户ID
        /// </summary>
        public int? UserId { get; set; }
        /// <summary>
        /// 权限ID
        /// </summary>
        public int? PowerId { get; set; }
        public int? StatusId { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime CreateAt { get; set; }
        public int? CreateUserId { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? ModifyAt { get; set; }
        public int? ModifyUserId { get; set; }

        [ForeignKey("PowerId")]
        [InverseProperty("tb_map_user_power")]
        public virtual tb_info_power? Power { get; set; }
        [ForeignKey("StatusId")]
        [InverseProperty("tb_map_user_power")]
        public virtual tb_info_status? Status { get; set; }
        [ForeignKey("UserId")]
        [InverseProperty("tb_map_user_power")]
        public virtual tb_info_user? User { get; set; }
        [InverseProperty("MapPower")]
        public virtual ICollection<tb_rec_authorize> tb_rec_authorize { get; set; }
    }
}