// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace NET6Demo.Model
{
    [Index("UserId", Name = "tb_map_user_roles_ibfk_1")]
    [Index("RoleId", Name = "tb_map_user_roles_ibfk_2")]
    [Index("StatusId", Name = "tb_map_user_roles_ibfk_3")]
    public partial class tb_map_user_roles
    {
        public tb_map_user_roles()
        {
            tb_rec_authorize = new HashSet<tb_rec_authorize>();
        }

        [Key]
        public int Id { get; set; }
        /// <summary>
        /// 用户ID
        /// </summary>
        public int? UserId { get; set; }
        /// <summary>
        /// 角色ID
        /// </summary>
        public int? RoleId { get; set; }
        public int? StatusId { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime CreateAt { get; set; }
        public int? CreateUserId { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? ModifyAt { get; set; }
        public int? ModifyUserId { get; set; }

        [ForeignKey("RoleId")]
        [InverseProperty("tb_map_user_roles")]
        public virtual tb_info_roles? Role { get; set; }
        [ForeignKey("StatusId")]
        [InverseProperty("tb_map_user_roles")]
        public virtual tb_info_status? Status { get; set; }
        [ForeignKey("UserId")]
        [InverseProperty("tb_map_user_roles")]
        public virtual tb_info_user? User { get; set; }
        [InverseProperty("MapRole")]
        public virtual ICollection<tb_rec_authorize> tb_rec_authorize { get; set; }
    }
}