// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace NET6Demo.Model
{
    [Index("UserId", Name = "tb_rec_authorize_ibfk_1")]
    [Index("MapPowerId", Name = "tb_rec_authorize_ibfk_2")]
    [Index("MapRoleId", Name = "tb_rec_authorize_ibfk_3")]
    public partial class tb_rec_authorize
    {
        [Key]
        public int Id { get; set; }
        /// <summary>
        /// 用户ID
        /// </summary>
        public int? UserId { get; set; }
        /// <summary>
        /// 用户与权限映射表ID
        /// </summary>
        public int? MapPowerId { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? createat { get; set; }
        /// <summary>
        /// 过期时间
        /// </summary>
        [Column(TypeName = "datetime")]
        public DateTime? AuthExp { get; set; }
        /// <summary>
        /// 刷新码
        /// </summary>
        [StringLength(255)]
        public string? RefrushCode { get; set; }
        /// <summary>
        /// 刷新码过期时间
        /// </summary>
        [Column(TypeName = "datetime")]
        public DateTime? RefrushExp { get; set; }
        /// <summary>
        /// 用户与角色映射表ID
        /// </summary>
        public int? MapRoleId { get; set; }
        [StringLength(255)]
        public string? Key { get; set; }

        [ForeignKey("MapPowerId")]
        [InverseProperty("tb_rec_authorize")]
        public virtual tb_map_user_power? MapPower { get; set; }
        [ForeignKey("MapRoleId")]
        [InverseProperty("tb_rec_authorize")]
        public virtual tb_map_user_roles? MapRole { get; set; }
        [ForeignKey("UserId")]
        [InverseProperty("tb_rec_authorize")]
        public virtual tb_info_user? User { get; set; }
    }
}