// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace NET6Demo.Model
{
    [Keyless]
    public partial class vw_org_license
    {
        public int Id { get; set; }
        /// <summary>
        /// 组织名称
        /// </summary>
        [StringLength(255)]
        public string? OrgName { get; set; }
        /// <summary>
        /// 组织编码
        /// </summary>
        [StringLength(100)]
        public string? OrgCode { get; set; }
        public int OrgId { get; set; }
        /// <summary>
        /// 授权类型名称
        /// </summary>
        [StringLength(255)]
        public string? LicName { get; set; }
        /// <summary>
        /// 授权类型说明
        /// </summary>
        [StringLength(1000)]
        public string? LicNote { get; set; }
        /// <summary>
        /// 状态名称
        /// </summary>
        [StringLength(255)]
        public string? Status { get; set; }
        /// <summary>
        /// 开始时间
        /// </summary>
        [Column(TypeName = "datetime")]
        public DateTime? Start { get; set; }
        /// <summary>
        /// 结束时间
        /// </summary>
        [Column(TypeName = "datetime")]
        public DateTime? End { get; set; }
    }
}