// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace NET6Demo.Model
{
    [Keyless]
    public partial class vw_org_user_role
    {
        public int Id { get; set; }
        /// <summary>
        /// 组织ID
        /// </summary>
        public int? OrgId { get; set; }
        /// <summary>
        /// 组织名称
        /// </summary>
        [StringLength(255)]
        public string? OrgName { get; set; }
        /// <summary>
        /// 用户ID
        /// </summary>
        public int? UserId { get; set; }
        /// <summary>
        /// 用户名称（昵称）
        /// </summary>
        [StringLength(255)]
        public string? UserName { get; set; }
        /// <summary>
        /// 角色名称
        /// </summary>
        [StringLength(255)]
        public string? RoleName { get; set; }
        public int? StatusId { get; set; }
        /// <summary>
        /// 状态名称
        /// </summary>
        [StringLength(255)]
        public string? Status { get; set; }
    }
}