// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace NET6Demo.Model
{
    [Keyless]
    public partial class vw_role_power
    {
        public int Id { get; set; }
        /// <summary>
        /// 角色名称
        /// </summary>
        [StringLength(255)]
        public string? RoleName { get; set; }
        /// <summary>
        /// 角色说明
        /// </summary>
        [StringLength(1000)]
        public string? RoleNote { get; set; }
        /// <summary>
        /// 权限名称
        /// </summary>
        [StringLength(255)]
        public string? PowerName { get; set; }
        /// <summary>
        /// 权限说明
        /// </summary>
        [StringLength(1000)]
        public string? PowerNote { get; set; }
        public int? StatusId { get; set; }
        /// <summary>
        /// 状态名称
        /// </summary>
        [StringLength(255)]
        public string? Status { get; set; }
    }
}